### ISSUE TITLE
Published package contains all files

### ISSUE THREAD

**Issue by Hdoc1509** [Naramatsu/kromac-ui-react#1]
Hi @Naramatsu, this package is publishing all files of this repo, as you can see in [npmjs.com](https://www.npmjs.com/package/kromac-ui-18?activeTab=code):

![kromac-ui-files](https://github.com/Naramatsu/kromac-ui-react/assets/72316111/a379c5f0-ad20-4a6f-a67a-35762c8c4670)

I recommend to set [`files` field in `package.json`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#files) to avoid this if it is not intended.

**Comment by Naramatsu** [comment]
> Hi @Naramatsu, this package is publishing all files of this repo, as you can see in [npmjs.com](https://www.npmjs.com/package/kromac-ui-18?activeTab=code):
> 
> ![kromac-ui-files](https://private-user-images.githubusercontent.com/72316111/316254596-a379c5f0-ad20-4a6f-a67a-35762c8c4670.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMzkxMDUsIm5iZiI6MTcxMTIzODgwNSwicGF0aCI6Ii83MjMxNjExMS8zMTYyNTQ1OTYtYTM3OWM1ZjAtYWQyMC00YTZmLWE2N2EtMzU3NjJjOGM0NjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDAwMDY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NDhhNzk4ZGYyOThhZDgxYzY0OWVlYzE3ZDJhNGJlNGY5OTE0ZTJlZDgzYzAyYThhMzNhODFhNGJhMmNmYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mKRZTDjQ-OILYl0aNrMquzUSE5p3fWRQOLeQm3FAiMo)
> 
> I recommend to set [`files` field in `package.json`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#files) to avoid this if it is not intended.

Hello @Hdoc1509 Thanks for the advice, I already fixed the above in version 1.3.2.

**Comment by Naramatsu** [comment]
I already fixed the above in version 1.3.2.
