### ISSUE TITLE
Development tools in dependencies

### ISSUE THREAD

**Issue by Hdoc1509** [Naramatsu/kromac-ui-react#3]
Hi @Naramatsu.

Checking the `package.json` of the project I saw some development tools that are in `dependencies`, like `@testing-library` packages, `react-script` and `html-react-parser`.

I recommend to read [package.json `dependencies` on npmDocs](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#dependencies) and check [package.json of `@mui/material`](https://github.com/mui/material-ui/blob/master/packages/mui-material/package.json) to set `dependencies`,  `devDependencies` and `peerDependencies` correctly.

**Comment by Naramatsu** [comment]
Hello @Hdoc1509 Thanks for the advice, I already remove all devDependencies from the package in version 1.3.2.
